config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  get "sell+rollex+in+nyc" => "page#sell_rolex_in_nyc", as: :rolex_nyc

  get "sell+or+pawn+wathes+nyc" =>  "page#sell_or_pawn_watches_in_queens", as: :sell_or_pawn

  get "where+to+sell+watches+in+queens" => "page#where_to_sell_wathces_in_queens", as: :where_to_sell

  get "sell+my+wathces+for+cash+in+queens" =>  "page#sell_my_watches_for_cash_in_queens", as: :watches_for_cash

  get "how+can+i+sell+my+watches+in+nyc" => "page#how_can_i_sell_my_watch_in_nyc", as: :how_can_i

  get "place+that+buys+watches+in+nyc" =>  "page#place_that_bay_watches_nyc", as: :place_that_buys

  get "stores+that+buys+watches+in+queens" => "page#stores_in_queens_that_buys_watches", as: :stores_that

   root 'page#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    @title = "sell watches in nyc | watch buyers in new york"
    @description = "We Specialize In Buying Watches In New York Area. Top Cash For Your Watches."
    @key_words = ["watchs", "watch","nyc","buy","sell", "trade","rolex","cash"]
    @h1 = "WE PAY TOP DOLLAR FOR WATCHES IN NEW YORK."
    @h2 = "We Buy Almost All Watches In NYC"
    @main_text = "Often people do not understand how important
 it is to know right place to sell their items. Especially
 if they are selling something expensive like watches. Our
experts know everything about luxury, fashion, vintage watches etc
. So if you want to sell your items and get your top dollar,
you are on the right page. We always pay more."
    render "template"
  end
  def sell_rolex_in_nyc
    @title = "Sell Rolex In NYC | Rolex buyers in new york"
    @description = "We Specialize In Buying Rolex Watches In New York Area. Top Cash For Your Watches."
    @key_words = ["Rolex" , "watchs", "watch","nyc","buy","sell", "trade","rolex","cash"]
    @h1 = "WE PAY TOP DOLLAR FOR WATCHES IN NEW YORK."
    @h2 = "We Buy Almost All Watches In NYC"
    @main_text = "Often people do not understand how important
 it is to know right place to sell their items. Especially
 if they are selling something expensive like watches. Our
experts know everything about luxury, fashion, vintage watches etc
. So if you want to sell your items and get your top dollar,
you are on the right page. We always pay more."
    render "template"
  end

  def sell_or_pawn_watches_in_queens
    @title = "Sell Or Pawn Watches In QUEENS | PAWN WATCHES IN NYC"
    @description = "We Specialize In Buying Watches In New York Area. Top Cash For Your Watches."
    @key_words = ["Pawn", "watchs", "watch","nyc","buy","sell", "trade","rolex","cash"]
    @h1 = "WE PAY TOP DOLLAR FOR WATCHES IN NEW YORK."
    @h2 = "We Buy Almost All Watches In NYC"
    @main_text = "Often people do not understand how important
 it is to know right place to sell their items. Especially
 if they are selling something expensive like watches. Our
experts know everything about luxury, fashion, vintage watches etc
. So if you want to sell your items and get your top dollar,
you are on the right page. We always pay more."
    render "template"
  end

  def where_to_sell_wathces_in_queens
    @title = "Where Can I sell Watches In queens | NYC BEST PLACE TO SELL WATCHES "
    @description = "We Specialize In Buying Watches In New York Area. Top Cash For Your Watches."
    @key_words = ["watchs", "watch","nyc","buy","sell", "trade","rolex","cash"]
    @h1 = "WE PAY TOP DOLLAR FOR WATCHES IN NEW YORK."
    @h2 = "We Buy Almost All Watches In NYC"
    @main_text = "Often people do not understand how important
 it is to know right place to sell their items. Especially
 if they are selling something expensive like watches. Our
experts know everything about luxury, fashion, vintage watches etc
. So if you want to sell your items and get your top dollar,
you are on the right page. We always pay more."
    render "template"
  end

  def sell_my_watches_for_cash_in_queens
    @title = "SELL MY WAtHCES FOR CASH IN QUEENS | NYC WATCHES BUYERS"
    @description = "We Specialize In Buying Watches In New York Area. Top Cash For Your Watches."
    @key_words = ["watchs", "watch","nyc","buy","sell", "trade","rolex","cash"]
    @h1 = "WE PAY TOP DOLLAR FOR WATCHES IN NEW YORK."
    @h2 = "We Buy Almost All Watches In NYC"
    @main_text = "Often people do not understand how important
 it is to know right place to sell their items. Especially
 if they are selling something expensive like watches. Our
experts know everything about luxury, fashion, vintage watches etc
. So if you want to sell your items and get your top dollar,
you are on the right page. We always pay more."
    render "template"
  end

  def how_can_i_sell_my_watch_in_nyc
    @title = "HOW CAN i sell my watches in queens | where to sell watches in nyc"
    @description = "We Specialize In Buying Watches In New York Area. Top Cash For Your Watches."
    @key_words = ["watchs", "watch","nyc","buy","sell", "trade","rolex","cash"]
    @h1 = "WE PAY TOP DOLLAR FOR WATCHES IN NEW YORK."
    @h2 = "We Buy Almost All Watches In NYC"
    @main_text = "Often people do not understand how important
 it is to know right place to sell their items. Especially
 if they are selling something expensive like watches. Our
experts know everything about luxury, fashion, vintage watches etc
. So if you want to sell your items and get your top dollar,
you are on the right page. We always pay more."
    render "template"
  end

  def place_that_bay_watches_nyc
    @title = "sell watches in nyc | watch buyers in new york"
    @description = "We Specialize In Buying Watches In New York Area. Top Cash For Your Watches."
    @key_words = ["watchs", "watch","nyc","buy","sell", "trade","rolex","cash"]
    @h1 = "WE PAY TOP DOLLAR FOR WATCHES IN NEW YORK."
    @h2 = "We Buy Almost All Watches In NYC"
    @main_text = "Often people do not understand how important
 it is to know right place to sell their items. Especially
 if they are selling something expensive like watches. Our
experts know everything about luxury, fashion, vintage watches etc
. So if you want to sell your items and get your top dollar,
you are on the right page. We always pay more."
    render "template"
  end

  def stores_in_queens_that_buys_watches
    @title = "Stores in queens that buys watches | best place to sell my watches in NYC"
    @description = "We Specialize In Buying Watches In New York Area. Top Cash For Your Watches."
    @key_words = ["watchs", "watch","nyc","buy","sell", "trade","rolex","cash"]
    @h1 = "WE PAY TOP DOLLAR FOR WATCHES IN NEW YORK."
    @h2 = "We Buy Almost All Watches In NYC"
    @main_text = "Often people do not understand how important
 it is to know right place to sell their items. Especially
 if they are selling something expensive like watches. Our
experts know everything about luxury, fashion, vintage watches etc
. So if you want to sell your items and get your top dollar,
you are on the right page. We always pay more."
    render "template"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= metamagic %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>



  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

  <meta name="author" content="">



<%= render "shared/css" %>

</head>
<body id="page-top" class="index">



<%= yield %>



<%= render "shared/js" %>
</body>
</html>

app/views/page/index.html.erb
<h1>Hello World</h1>

app/views/page/template.html.erb
<%
   meta title: @title.upcase!,
        description: @deskription,
        keywords: @key_words
%>
<%= render "shared/navigation" %>


<!-- Services Section -->
<section id="services">
  <div class="container">
    <% if controller.controller_name == "page" && controller.action_name == "index" %>
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">What We Buy?</h2>
        <h2 class="section-heading"> We Buy Almost All Watches In NYC </h2>
      </div>
    </div>
    <div class="row text-center watches">
      <div class="col-md-6">
        <h3><a href="#">Rolex Watches</a></h3>
        <h3><a href="#">IWC Schaffhausen</a></h3>
        <h3><a href="#">Patek Philippe Watches</a></h3>
        <h3><a href="#">Citizen Watches</a></h3>
        <h3><a href="#">Bulova Watches</a></h3>
        <h3><a href="#">Seiko Watches</a></h3>
        <h3><a href="#">Omega  Watches</a></h3>
        <h3><a href="#">Tissot  Watches</a></h3>
      </div>
      <div class="col-md-6">
        <h3><a href="#">Hamilton Watches</a></h3>
        <h3><a href="#">Tag Heuer Watches</a></h3>
        <h3><a href="#">FOSSIL Watches</a></h3>
        <h3><a href="#">Breitling Watches</a></h3>
        <h3><a href="#">Cartier Watches</a></h3>
        <h3><a href="#">Piaget Watches</a></h3>
        <h3><a href="#">Breguet Watches</a></h3>
        <h3><a href="#">Audemars  Watches</a></h3>
      </div>
    </div>
        <% else %>
        <div class="col-lg-12 text-center">
          <h2 class="section-heading"> <%= @h2 %> </h2>
        </div>
        <% end %>
    <div class="row">
      <p class="main_text"><%= @main_text %></p>
    </div>
  </div>
</section>




<!-- Services Section -->
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Popular searches</h2>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-4">
        <%= link_to "Sell Rolex in NYC",  rolex_nyc_path %> <br/>
        <%= link_to "Sell or pawn watches in NYC", sell_or_pawn_path %>

      </div>
      <div class="col-md-4">
        <%= link_to "Where to sell watches in Queens", where_to_sell_path %> <br/>
        <%= link_to "Sell my watches for cash in Queens", watches_for_cash_path %> <br/>
        <%= link_to "How can i sell my wathces in NYC", how_can_i_path %>
      </div>
      <div class="col-md-4">
        <%= link_to "Place that buys watches in NYC", place_that_buys_path%> <br/>
        <%= link_to "Stores that buys watches in Queens", stores_that_path %>
      </div>
    </div>
  </div>
</section>





<!-- Contact Section -->
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Contact Us</h2>
        <h3 class="section-subheading text-muted"> <a href="tel:+1-718-846-1600"> tel: +1 (718) 846-1600 </a> <br> <br>
          <a href="https://www.google.com/maps/dir/Current+Location/8710+Lefferts+BLVD+Richmond+Hill+NY+11418"><i class="fa fa-map-marker"> </i>Location in Queens</a> </h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
       <%= render "shared/mailForm" %>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">SellWatches.NYC &copy; 2015</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li><a href="https://twitter.com/webuygoodsnyc"><i class="fa fa-twitter"></i></a>
          </li>
          <li><a href="https://www.facebook.com/webuygoodsnyc"><i class="fa fa-facebook"></i></a>
          </li>
          <li><a href="https://plus.google.com/106507584776418285314/about"><i class="fa fa-google-plus"></i></a>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="list-inline quicklinks">
          <li><a href="http://www.webuygoods.com">WeBuyGoods.com</a>
          </li>
          <li><a href="http://sellelectronics.nyc">SellElectronics.NYC</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_css.html.erb
<!-- Bootstrap Core CSS -->
<link href="css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS -->
<link href="css/agency.css" rel="stylesheet">
<!-- Custom Fonts -->
<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

app/views/shared/_js.html.erb
<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Plugin JavaScript -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="js/classie.js"></script>
<script src="js/cbpAnimatedHeader.js"></script>

<!-- Contact Form JavaScript -->
<script src="js/jqBootstrapValidation.js"></script>
<script src="js/contact_me.js"></script>

<!-- Custom Theme JavaScript -->
<script src="js/agency.js"></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

app/views/shared/_mailForm.html.erb
<form name="sentMessage" id="contactForm" novalidate>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Your Name *" id="name" required data-validation-required-message="Please enter your name.">
        <p class="help-block text-danger"></p>
      </div>
      <div class="form-group">
        <input type="email" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address.">
        <p class="help-block text-danger"></p>
      </div>
      <div class="form-group">
        <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required data-validation-required-message="Please enter your phone number.">
        <p class="help-block text-danger"></p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <textarea class="form-control" placeholder="Your Message *" id="message" required data-validation-required-message="Please enter a message."></textarea>
        <p class="help-block text-danger"></p>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-lg-12 text-center">
      <div id="success"></div>
      <button type="submit" class="btn btn-xl">Send Message</button>
    </div>
  </div>
</form>

app/views/shared/_mail_ruby.html.erb
<%= form_tag("/page/send_email", method: "get", class: "contactForm", name: "sentMessage") do %>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= text_field_tag(:q, class: "form-control", placeholder: "Your Name *", id: "name") %>
          <p class="help-block text-danger"></p>
        </div>
        <div class="form-group">
          <input type="email" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address.">
          <p class="help-block text-danger"></p>
        </div>
        <div class="form-group">
          <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required data-validation-required-message="Please enter your phone number.">
          <p class="help-block text-danger"></p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <textarea class="form-control" placeholder="Your Message *" id="message" required data-validation-required-message="Please enter a message."></textarea>
          <p class="help-block text-danger"></p>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="col-lg-12 text-center">
        <div id="success"></div>
        <button type="submit" class="btn btn-xl">Send Message</button>
      </div>
    </div>


    <%= text_field_tag(:q) %>

    <%= text_field_tag(:q) %>

    <%= submit_tag("Search") %>
<% end %>

app/views/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">SellWatche.NYC</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <a class="page-scroll" href="https://www.google.com/maps/dir/Current+Location/8710+Lefferts+BLVD+Richmond+Hill+NY+11418">
            <i class="fa fa-map-marker"></i> Location</a>
        </li>
        <li>
          <a class="page-scroll" href="#services">What We Buy</a>
        </li>
        <li>
          <a class="page-scroll" href="#contact">Contact</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<!-- Header -->
<header>
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">Welcome To SellWatch NYC</div>
      <h1><div class="intro-heading"><%= @h1 %></div></h1>
      <a href="tel:+1-718-846-1600" class="page-scroll btn btn-xl"> <i class="fa fa-phone"></i> 718-846-1600 - Call Now!  </a>

    </div>
  </div>
</header>